GET http://localhost:5000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzQxNDc0MTgzLCJleHAiOjE3NDIwNzg5ODN9.gRfO2XwS0rmjJeRJhiKzga5fiv-X-w7SA7PlDAJKM4w
### Create User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{

  "email": "alan-the@gmail.com",
  "password": "Password123"
}
 